import time,os,sys,webbrowser

#Functies die ik gebruik voor looks:
def clearscreen(numlines=151):
  if os.name in ("nt", "dos", "ce"):
    os.system('CLS')
  else:
    print('\n' * numlines)

def typPrint(text):
  for character in text:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(0.07)


#Alle functies die het verhaal bij elkaar brengen:
def NederlandEind():
    print("")
    typPrint("We werden grondig ondervraagd, vragen zoals waar we vandaan kwamen en wat ons bezoek hier in Nederland.")
    print("")
    typPrint("We vroegen naar ze over een visum en hun zeiden dat dat een tijdje kan duren aangezien er nu heel veel mensen uit Syrie komen vluchtennaar Nederland.")
    print("")
    typPrint("Na een nacht in de cel te hebben gespendeerd werden we opgehaald om naar een opvangkamp te gaan en een visum aan te vragen.")
    print("")
    typPrint("2 maanden later hadden we ons visum, en we hadden nu al zoveel meegemaakt dat we besloten te blijven in Nederland, een baan te zoeken en natuurlijk ik naar school.")
    print("")
    typPrint("Nu 2 jaar later ben ik een officieel burger van Nederland en ken ik de taal vlekkeloos, en ik zou hier nooit meer weg willen.")
    print("")
    typPrint("FIN")
    print("")
    print("")
    time.sleep(1)
    clearscreen()
    typPrint("Exiting Please wait")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    exit()

def Nederland1():
    print("")
    typPrint("Ik en me moeder hadden besloten om naar Nederland te gaan. Met het geld dat we hadden verdiend in Griekenland koopten we eerst tickets naar Oostenrijk")
    print("")
    typPrint("We waren in de bus 1,5 week onderweg met een aantal tussenstops. Vanuit Oostenrijk zouden we weer met de bus naar Duitsland reizen.")
    print("")
    typPrint("Zo konden we via duitsland de Thalys nemen naar Nederland, en os visum aanvragen.")
    print("")
    typPrint("Eenmaal aangekomen in Nederland na 5 dagen, waren we vermoeid en hadden we geen put meer over dus we sliepen op straat.")
    print("")
    typPrint("We werden midden in de nacht wakker gemaakt door de Politie en naar bureau meegenomen voor ondervraging, gelukkig hadden ze een tolk want we konden toen nog geen Nederlands")
    clearscreen()
    NederlandEind()

def blijvenG1():
    print("")
    typPrint("Me moeder zei dat we hier moesten blijven, zodat we nog niet te ver van huis waren en altijd makkelijk terug konden.")
    print("")
    typPrint("Na 2 maanden wachten hadden we ons visum en konden we blijven, een huis uitzoeken en werk zoeken.")
    print("")
    typPrint("Ik ging uiteindelijk weer naar school, en moest hard studeren om hun taal te leren om alles bij te houden.")
    print("")
    typPrint("uiteindelijk is alles goed gekomen en hebben we ons eigen huis in Griekenland, wachtend op de dag dat we kunnen terugkeren.")
    print("")
    typPrint("FIN")
    print("")
    print("")
    time.sleep(1)
    typPrint("Exiting Please wait")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    exit()

def meerkeuze1G():
    print("")
    print("")
    answer = input("Blijf je in Griekenland proberen, of ga je naar Nederland?\nAntwoord met <G> voor Griekenland, <N> om naar Nederland te gaan: ") 
    if answer == "G": 
        
        print("")
        typPrint("Je blijft in Griekenland proberen")
        time.sleep(1)
        clearscreen()
        blijvenG1()

    elif answer == "N": 
         
        print("")
        typPrint("Je gaat nu onderweg naar Nederland")
        clearscreen()
        Nederland1()
    
    elif answer == "Q":
        clearscreen()
        print("")
        time.sleep(1)
        typPrint("Exiting by input command")
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        exit()
    
    else: 
    	
        print("")
        print("Please Enter <G> or <N> to continue!")
        time.sleep(2)
        clearscreen()
        meerkeuze1G() 

def griekenland1():
    print("")
    typPrint("In Griekenland duurde het heel lang voordat we een verblijfsvergunning konden krijgen.")
    print("")
    typPrint("Mijn moeder dacht eraan om naar een ander land heen te gaan waar het korter duurde.")
    print("")
    typPrint("Iedereen zei dat het proces in Nederland het kortste suurde, maar we hadden nog nooit gehoord van Nederland.")
    print("")
    typPrint("Ik vroeg aan me moeder waar dat lag, en ze zei helemaal in het noorden")
    time.sleep(1)
    clearscreen()
    meerkeuze1G()  

def vluchten2():
    print("")
    typPrint("We bleven in Istanbul voor 2 weken en hadden een klein huisje ter onze beschikking.")
    print("")
    typPrint("Na die 2 weken moesten we doorreizen naar Edirne, een stad vlak voor de grens naar Griekenland.")
    print("")
    typPrint("Na 4 dagen verder reizen waren we daar aangekomen, we probeerden via daar over de grens te komen naar Griekenland.")
    print("")
    typPrint("We kwamen uitendelijk de grens over naar griekenland met het idee om later weer terug te gaan naar Syrie.")
    print("")
    typPrint("Uiteindelijk was het ons gelukt om in griekenland gezet te worden naar een kamp waar allemaal vluchtelingen waren, het kamp Morio.")
    clearscreen()
    griekenland1()

def opbouwen(): 
    print("")
    typPrint("Eenmaal aangekomen, begonnen we alles op te rapen wat bruikbaar was zoals stenen, eten, drinken, hout, metaal en gereedschap.")
    print("")
    typPrint("Omdat de Taliban in een paar shops hebben gezeten en huizen waren die nog heel en konden we daar alles in opbergen en er een tijdelijke slaapplek van maken.")
    print("")
    time.sleep(1)
    clearscreen()
    typPrint("De bouw ging vlot, al snel waren er hutten gebouwd voor opslag en huizen gerepareerd waar we terecht konden.")
    print("")
    typPrint("We werkten allemaal samen, en zo konden we binnen 2 maanden in een eigen bed slapen in aparte kamers/huizen.")
    print("")
    typPrint("We hebben tot nu aan toe niks meer gehoord van de Taliban, we bidden nogsteeds elke dag dat ze hier niet terug komen om alles te slopen wat we hadden opgebouwd.")
    print("")
    typPrint("FIN")
    clearscreen()
    print("")
    time.sleep(1)
    typPrint("Exiting by input command")
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    exit()

def eigenland2():
    print("")
    typPrint("De vrouwen en kinderen werden van de mannen gescheiden, en de mannen werden tegen de vangrail gezet en gefouilleerd.")
    print("")
    typPrint("Mijn moeder was aan het bidden, want ons leven hing ervan af. Even later vertelde de mannen dat ze in het verzet zaten en dat het nog niet veilig was.")
    print("")
    typPrint("Iedereen was opgelucht om te horen dat ze veilig waren. De mannen vertelden ook dat ze wel weg zijn uit Aleppo maar er niks meer van over is.")
    print("")
    typPrint("Iedereen zou stemmen, of we terug naar turkije gaan of dat we verdergaan omdat we al zo ver zijn.")
    print("")
    typPrint("Iemand gaf ook een speech dat we alles weer konden opbouwen. en dat we als team sterker stonden dan alleen.")
    print("")
    typPrint("Iedereen had besloten dat we verder gingen om alles weer op te bouwen en er zelf het beste van te maken. het was tenslotte ons tehuis.")
    clearscreen()
    time.sleep(1)
    opbouwen()

def turkije3():
    print("")
    typPrint("Me moeder besloot om te blijven in Turkije aangezien het maar wat geruchten waren en het ons leven kan kosten.")
    print("")
    typPrint("In Turkije waren we gelukkig, mijn moeder had al een baan gevonden en wij konden naar school in Turkije.")
    print("")
    typPrint("Me moeder maakte al snel vrienden, we begonnen al erg veel betrokken te raken in de gemeenschap.")
    print("")
    typPrint("Mijn moeder had hetnaar haar zin en besloot om hier langer te blijven dan nodig was.")
    time.sleep(1)
    print("")
    typPrint("Het is 2 jaar later, we zijn nu inwoners van turkije, ik doe de opleiding advocaat en me broertje zit op de middelabre school.")
    print("")
    typPrint("Mijn moeder en ik hebben besloten om te blijven en de oorlog uit te zitten in Istanbul, daar waar het veilig is.")
    print("")
    typPrint("FIN")
    clearscreen()
    time.sleep(1)
    typPrint("Exiting by input command")
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    exit()

def eigenland1():
    print("")
    typPrint("Me moeder had besloten, ze ging de gok wagen om weer terug te gaan naar Syrie, ons eigen land.")
    print("")
    typPrint("De reis zou lang duren, we zouden weer 1,5 week onderweg zijn maar mijn moeder had een busreis geregeld van istanbul naar Aleppo.")
    print("")
    typPrint("Het nieuws verspreidde zich snel, we zagen allemaal mensen op het buststation die we kenden van onze stad Aleppo.")
    print("")
    typPrint("Het was een gezellige busreis naar Aleppo, er werd gezongen gedanst en veel genoten van het eten dat we elkaar gaven. Iedereen was blij.")
    print("")
    typPrint("We maakten een paar tussenstops om onze honger en dorst te leggen, en reden daarna gelijk door.")
    print("")
    typPrint("De reis duurde 4 dagen, en we waren 10 minuten verwijderd van Aleppo op een grote snelweg en de bus werd belaagd door mensen met wapens.")
    clearscreen()
    eigenland2()

def meerkeuze1T():
    print("")
    print("")
    answer = input("Blijf je in Turkije, of ga je terug naar eigen land (Syrie)\nAntwoord met <T> voor blijven, <S> om weer naar Syrie te gaan: ") 
    if answer == "T": 
        
        print("")
        typPrint("Je blijft in Turkije")
        time.sleep(1)
        clearscreen()
        turkije3()

    elif answer == "S": 
         
        print("")
        typPrint("Je gaat weer terug naar Syrie")
        clearscreen()
        eigenland1()
    
    elif answer == "Q":
        clearscreen()
        print("")
        time.sleep(1)
        typPrint("Exiting by input command")
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        exit()
    
    else: 
    	
        print("")
        print("Please Enter <T> or <S> to continue!")
        time.sleep(2)
        clearscreen()
        meerkeuze1T() 

def turkije2():
    print("")
    typPrint("Mijn moeder hoorde van de buren dat ze verder getrokken waren naar het noorden.")
    print("")
    typPrint("Mijn moeder stond voor een lastige keuze, wat als het nou gelogen was en wat als het nou een valsstrik was om mensen gevangen te houden?")
    print("")
    typPrint("Keuze optie laden")
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    clearscreen()
    meerkeuze1T()   

def turkije1():
    print("")
    typPrint("We wilden niet ver van huis blijven, we hadden altijd het idee dat op een dag de oorlog over zou zijn.")
    print("")
    typPrint("En dat we daarna terug zouden keren naar ons eigen land.")
    print("")
    typPrint("We hadden nog hoop, we kregen een klein huisje toen we eenmaal gesettled waren in Tukrije voelden we ons weer vrij.")
    print("")
    typPrint("We konden gaan en staan waar we wilden, en moesten een tijdelijk verblijfsvergunning aanvragen toen we waren ingeburgerd.")
    print("")
    typPrint("Mijn moeder kreeg na een half jaar te horen dat we wel terug konden, omdat het gevecht in onze stad was afgelopen.")
    print("")
    clearscreen()
    turkije2()

def vluchteneinde():
    time.sleep(1)
    print("")
    print("")
    typPrint("Helaas eindigt hier het verhaal van Sara.")
    print("")
    typPrint("Sara word opgesloten in de gevangenis met haar vader.")
    print("")
    typPrint("Haar vader en Sara hebben al die tijd in de gevangenis gezeten smekend om te kunnen vertrekken of een 2e kans maar die niet kregen.")
    print("")
    typPrint("Uiteindelijk kwam er een rechtzaak tegen de vader van Sara, voor het verspreiden van leugens over het land en het verzet in het land.")
    print("")
    typPrint("De vader van Sara werd uiteindelijk veroordeeld tot de dood 2 weken na de uitspraak.")
    print("")
    typPrint("Sara heeft haar vader nooit meer gezien na die dag, en zit tot de dag van vandaag nogsteeds in de gevangenis, zwak, misbruikt en verkracht.")
    print("")
    typPrint("FIN")
    clearscreen()
    print("")
    print("")
    time.sleep(1)
    typPrint("Exiting")
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    exit()
    
def bezoeken2():
    print("")
    typPrint("Ik wist niet wat me overkwam.")
    print("")
    typPrint("De bewakers van de gevangenis dachten dat ik in het complot zat met mijn vader, maar dat ben ik niet.")
    print("")
    typPrint("Nou zit ik hier vast, ik ben onschuldig en alles wat ik ze vertel geloven ze niet.")
    print("")
    typPrint("Ze zeggen dat ze me gaan verkrachten, martelen en mijn famillie oppakken als ik niet de waarheid vertel.")
    print("")
    typPrint("Toch blijf ik zeggen dat ik het niet gedaan heb en houd ik mijn poot stijf.")
    print("")
    clearscreen()
    vluchteneinde()

def bezoeken():
    print("")
    typPrint("Eenmaal onderweg naar de gevangenis die 500 meter van ons huis vandaan is word ik raar aangekeken door de agenten die daar rondom staan.")
    print("")
    typPrint("Veel van die agenten en bewakers fluiten naar me om mijn aandacht te trekken.")
    print("")
    typPrint("Ik keek omlaag en liep recht naar de poort van de gevangenis.")
    print("")
    print("")
    typPrint("Eenmaal aangekomen bij de gevangenis moest ik mij identificeren voordat ik naar binnen mocht en grondig gefouilleerd worden.")
    print("")
    typPrint("Toen ik aan de bewakers vertelde wie ik kwam bezoeken lieten ze me meelopen naar een kamer achterin om mij te ondervragen")
    print("")
    typPrint("Ze vroegen aan mij wat ik van deze persoon was en ik antwoorde eerlijk met dat hij mijn vader was.")
    print("")
    typPrint("Uiteindelijk was het geen goed idee om te vertellen dat ik zijn dochter was, ik werd per direct opgepakt omdat ze informatie nodig hadden van mijn vader")
    print("")
    typPrint("Zodra ik die informatie zou geven zouden we beiden uit de gevangenis mogen zeiden ze.")
    print("")
    print("")
    typPrint("Ik was bang, en wist niet wat er gebeurde. Toen ik de informatie gaf die ze nodig hadden moest ik in die kamer blijven zitten totdat ze me ophaalden.")
    print("")
    typPrint("Uiteindelijk moest ik meekomen van de bewaker naar de kleedkamer. Ik moest me uitkleden en een pak aandoen dat ze hadden klaarliggen.")
    print("")
    typPrint("Ik kreeg een gevangenispak van de bewaker aangeboden, dus ik vroeg of dit betekende dat ik naar de gevangenis moest.")
    print("")
    typPrint("De bewaker lachte en liep weg. Uiteindelijk werd ik verplaatst naar mijn cel een zeiden ze dat ik het daglicht nooit meer zou zien. ")
    clearscreen()
    bezoeken2()

def meerkeuze1V():
    print("")
    print("")
    answer = input("Ga je door vluchten naar Griekenland, of ga je in Turkije blijven?\nAntwoord met <V> voor verder vluchten, <T> om in Turkije te blijven: ") 
    if answer == "V": 
        
        print("")
        typPrint("Je gaat nu verder in Turkije")
        time.sleep(1)
        clearscreen()
        turkije1()

    elif answer == "T": 
         
        print("")
        typPrint("Je gaat nu verder vluchten naar Griekenland")
        clearscreen()
        vluchten2()
    
    elif answer == "Q":
        clearscreen()
        print("")
        time.sleep(1)
        typPrint("Exiting by input command")
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        exit()
    
    else: 
    	
        print("")
        print("Please Enter <V> or <T> to continue!")
        time.sleep(2)
        clearscreen()
        meerkeuze1V()  

def vluchten1():
    print("")
    typPrint("Toen was het tijd om te vluchten, mijn vader was opgepakt en ik bleef over met mijn zusje en moeder.")
    print("")
    typPrint("Mijn moeder besloot om naar Turkije te vluchten. ")
    print("")
    typPrint("We pakten alleen wat we nodig hadden en vertrokken naar Turkije.")
    print("")
    typPrint("Het was een lange reis en na 2 weken waren we aangekomen in Istanbul. ")
    print("")
    typPrint("Keuze optie laden")
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    clearscreen()
    meerkeuze1V()

def Syrië1():
    print("")
    typPrint("Mijn ouders probeerden er het beste van te maken. ’s Avonds vertelden we elkaar verhalen en lazen boekjes. Dan voelde ik me voor even veilig.")
    print("")
    typPrint("Mijn vader zat in het verzet tegen de oorlog.")
    print("")
    typPrint("Het werd steeds gevaarlijker in Aleppo. Mijn vader werd toen opgepakt wegens zijn daden")
    print("")
    typPrint("Ik moest en zal mijn vader toen zien, maar mijn moeder zegt dat ik dan ook opgepakt kan worden.")
    print("")
    typPrint("Keuze optie laden")
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    print(".")
    time.sleep(1)
    clearscreen()
    meerkeuze2()

def meerkeuze2():    
    print("")
    print("")
    answer = input("Ga je je vader bezoeken en erop gokken dat je niet word opgepakt of ga je vluchten naar een ander land?\nAntwoord met <B> voor bezoeken, <V> om te vluchten: ") 
    if answer == "B": 
        
        print("")
        typPrint("Je gaat nu je vader proberen te bezoeken.")
        time.sleep(1)
        clearscreen()
        bezoeken()

    elif answer == "V": 
         
        print("")
        typPrint("Je gaat nu proberen te vluchten.")
        clearscreen()
        vluchten1()
    
    elif answer == "Q":
        clearscreen()
        print("")
        time.sleep(1)
        typPrint("Exiting by input command")
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        exit()
    
    else: 
    	
        print("")
        print("Please Enter <B> or <V> to continue!")
        time.sleep(2)
        clearscreen()
        meerkeuze2() 

def mkinleiding1(): 
    print("")
    typPrint("Het geweld in Syrië neemt snel toe, Verschillende partijen strijden met elkaar en Aleppo wordt zwaar gebombardeerd.")
    print("")
    typPrint("Ik wist niet wat een oorlog was of wat bommen betekenden. De dag ervoor waren we gezellig op bezoek bij familie.")
    print("")
    typPrint("Een dag later valt er een bom en zie ik allemaal gewonde en dode mensen op straat liggen.")
    print("")
    typPrint("Toen werd ik wel bang, ik kon niet geloven dat dit echt gebeurde.")
    meerkeuze1()

def meerkeuze1():    
    print("")
    print("")
    answer = input("Wil je door met het leven in Syrië, of wil je vluchten naar een ander land?\nAntwoord met <S> voor Syrië, <A> om naar een ander land te gaan. ") 
    if answer == "S": 
        
        print("")
        typPrint("Goed laten we wat verder gaan met het leven in Syrië")
        time.sleep(1)
        clearscreen()
        Syrië1()

    elif answer == "A": 
         
         print("")
         typPrint("Goed laten we vluchten naar een ander land.")
         clearscreen()
         Nederland1()
    
    elif answer == "Q":
        clearscreen()
        print("")
        time.sleep(1)
        typPrint("Exiting by input command")
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        typPrint(".")
        time.sleep(1)
        exit()
    
    else: 
    	
        print("")
        print("Please Enter <S> or <N> to continue!")
        time.sleep(2)
        clearscreen()
        meerkeuze1() 
        
def inleiding():
    print("")
    typPrint("Sara is zes als ze met haar zusje en ouders een gelukkig leven leidt in Aleppo, Syrië.")
    print("")
    typPrint("Totdat het opeens helemaal mis gaat. 'Het leek zo’n normale nacht. ")
    print("")
    typPrint("Mijn zusje en ik waren sterren aan het tellen. Opeens hoorden we een heel hard geluid. ")
    print("")
    typPrint("We renden naar onze ouders en vroegen wat eraan de hand was. Zij wisten het ook niet. '")
    print("")
    typPrint("Pas na een paar dagen werd het ons duidelijk: de oorlog was begonnen.")
    time.sleep(1)
    typPrint(".")
    time.sleep(1)
    typPrint(".")
    clearscreen()
    mkinleiding1()

def start(): 
    typPrint("Hello you! En welkom bij mijn BeroepsOpdracht.")
    print("")
    typPrint("In deze opdracht ga ik een verhaal vertellen over Sara")
    print("")
    typPrint("Sara is afkomstig uit Syrië, en is gevlugt uit haar eigen land naar vrijheid.")
    print("")
    typPrint("In dit verhaal kun je ook een andere richting op gaan met meerkeuze antwoorden.")
    print("")
    typPrint(" Elke richting bied een andere kant van het verhaal.")
    print("")
    typPrint("Ook kun je het verhaal uitgaan door bij elke vraag hoofdletter <Q> in te vullen bij het antwoorden.")
    print("")   
    typPrint("Ik hoop dat ik je hiermee genoeg geÏnformeerd heb.")
    print("")
    time.sleep(1)
    typPrint("Veel plezier met het beleven van het verhaal van Sara.")
    time.sleep(2)
    clearscreen()
    inleiding()

start()